### ISSUE TITLE
./Home returns 404

### ISSUE THREAD

**Issue by Douile** [ElliottDG/F1-Stats#30]
When visiting https://elliottdg.github.io/F1-Stats the URL is rewritten to https://elliottdg.github.io/F1-Stats/Home, which doesn't exist so the when refreshing the server responds with 404. This prevents lighthouse from running.

**Comment by ElliottDG** [comment]
fixed by 7a25b7a2fb1dd2915db8ca724995e197882ab0a1

**Comment by ElliottDG** [comment]
![image](https://github.com/ElliottDG/F1-Stats/assets/66923682/184f9ad7-99fa-4eea-9e8d-24372edfb812)
